// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhanVatGame.Data;

#nullable disable

namespace NhanVatGame.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NhanVatGame.Models.Class", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("NhanVatGame.Models.KyNang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ManaCanDung")
                        .HasColumnType("int");

                    b.Property<string>("TenKyNang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KyNangs");
                });

            modelBuilder.Entity("NhanVatGame.Models.KyNangNhanVat", b =>
                {
                    b.Property<string>("NhanVatID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KyNangID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NhanVatID", "KyNangID");

                    b.HasIndex("KyNangID");

                    b.ToTable("KyNangNhanVats");
                });

            modelBuilder.Entity("NhanVatGame.Models.NguoiDung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SDT")
                        .HasColumnType("int");

                    b.Property<string>("TaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("NhanVatGame.Models.NhanVat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HP")
                        .HasColumnType("int");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("Mana")
                        .HasColumnType("int");

                    b.Property<string>("NguoiDungID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNhanVat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VuKhiID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClassID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("VuKhiID");

                    b.ToTable("NhanVats");
                });

            modelBuilder.Entity("NhanVatGame.Models.VuKhi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenVuKhi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuocTinhVuKhi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VuKhis");
                });

            modelBuilder.Entity("NhanVatGame.Models.KyNangNhanVat", b =>
                {
                    b.HasOne("NhanVatGame.Models.KyNang", "KyNang")
                        .WithMany("KyNangNhanVats")
                        .HasForeignKey("KyNangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhanVatGame.Models.NhanVat", "NhanVat")
                        .WithMany("KyNangNhanVats")
                        .HasForeignKey("NhanVatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyNang");

                    b.Navigation("NhanVat");
                });

            modelBuilder.Entity("NhanVatGame.Models.NhanVat", b =>
                {
                    b.HasOne("NhanVatGame.Models.Class", "Class")
                        .WithMany("NhanVatEntities")
                        .HasForeignKey("ClassID");

                    b.HasOne("NhanVatGame.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhanVats")
                        .HasForeignKey("NguoiDungID");

                    b.HasOne("NhanVatGame.Models.VuKhi", "VuKhi")
                        .WithMany("NhanVats")
                        .HasForeignKey("VuKhiID");

                    b.Navigation("Class");

                    b.Navigation("NguoiDung");

                    b.Navigation("VuKhi");
                });

            modelBuilder.Entity("NhanVatGame.Models.Class", b =>
                {
                    b.Navigation("NhanVatEntities");
                });

            modelBuilder.Entity("NhanVatGame.Models.KyNang", b =>
                {
                    b.Navigation("KyNangNhanVats");
                });

            modelBuilder.Entity("NhanVatGame.Models.NguoiDung", b =>
                {
                    b.Navigation("NhanVats");
                });

            modelBuilder.Entity("NhanVatGame.Models.NhanVat", b =>
                {
                    b.Navigation("KyNangNhanVats");
                });

            modelBuilder.Entity("NhanVatGame.Models.VuKhi", b =>
                {
                    b.Navigation("NhanVats");
                });
#pragma warning restore 612, 618
        }
    }
}
